import 'dart:convert';
import 'package:flutter/foundation.dart' show debugPrint;
import 'package:encrypt/encrypt.dart';

/// AES-256-CBC encryption service for QR code data.
///
/// Only the Healthy Bhai app knows the secret key, so QR codes scanned
/// by third-party readers will show unreadable ciphertext.
class QrCryptoService {
  // 32-byte key for AES-256
  static const String _secretKey = 'HlthyBh@i2026!SecretK3y#QrDat@XZ';

  // Magic header to verify the decrypted data came from our app
  static const String _magicHeader = 'HB_V1:';

  /// Encrypts a data map into a base64 string suitable for QR encoding.
  ///
  /// The data is JSON-encoded, prefixed with a magic header, then
  /// AES-256-CBC encrypted. The IV is prepended to the ciphertext
  /// so decryption can recover it.
  static String encrypt(Map<String, dynamic> data) {
    final key = Key.fromUtf8(_secretKey);
    final iv = IV.fromSecureRandom(16);
    final encrypter = Encrypter(AES(key, mode: AESMode.cbc));

    final plainText = '$_magicHeader${jsonEncode(data)}';
    final encrypted = encrypter.encrypt(plainText, iv: iv);

    // Prepend IV (base64) + ':' + ciphertext (base64)
    return '${iv.base64}:${encrypted.base64}';
  }

  /// Decrypts a QR code string back into a data map.
  ///
  /// Returns `null` if:
  /// - The string is not in the expected format
  /// - Decryption fails (wrong key / corrupted data)
  /// - The magic header is missing (not generated by our app)
  static Map<String, dynamic>? decrypt(String cipherText) {
    try {
      final parts = cipherText.split(':');
      if (parts.length < 2) {
        debugPrint('[QR Decrypt] Invalid format: no ":" separator found');
        return null;
      }

      final ivBase64 = parts[0];
      final encryptedBase64 = parts.sublist(1).join(':');

      debugPrint('[QR Decrypt] IV length: ${ivBase64.length}, cipher length: ${encryptedBase64.length}');

      final key = Key.fromUtf8(_secretKey);
      final iv = IV.fromBase64(ivBase64);
      final encrypter = Encrypter(AES(key, mode: AESMode.cbc));

      final decrypted = encrypter.decrypt64(encryptedBase64, iv: iv);

      // Verify magic header
      if (!decrypted.startsWith(_magicHeader)) {
        debugPrint('[QR Decrypt] Magic header mismatch. Got: ${decrypted.substring(0, decrypted.length.clamp(0, 20))}...');
        return null;
      }

      final jsonStr = decrypted.substring(_magicHeader.length);
      debugPrint('[QR Decrypt] Successfully decrypted data');
      return jsonDecode(jsonStr) as Map<String, dynamic>;
    } catch (e) {
      debugPrint('[QR Decrypt] Decryption error: $e');
      return null;
    }
  }
}
