// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFivC3PsM8xTanFNfjtN5mlIUdIHq9arY',
    appId: '1:510409085828:web:4cb0bef8e7040a581e03d1',
    messagingSenderId: '510409085828',
    projectId: 'healthybhai-b2791',
    authDomain: 'healthybhai-b2791.firebaseapp.com',
    storageBucket: 'healthybhai-b2791.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH7zfODmcL16JNh7I794N6Zzg_atKJOiA',
    appId: '1:510409085828:android:ed978f3c54cc8c0a1e03d1',
    messagingSenderId: '510409085828',
    projectId: 'healthybhai-b2791',
    storageBucket: 'healthybhai-b2791.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzG4ByapSRQSfhRKXQDURfBJUxY0EYR50',
    appId: '1:510409085828:ios:717b1b475d4b00931e03d1',
    messagingSenderId: '510409085828',
    projectId: 'healthybhai-b2791',
    storageBucket: 'healthybhai-b2791.firebasestorage.app',
    iosClientId: '510409085828-akfk75uc4doaap04t9mgnhlac35t218e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzG4ByapSRQSfhRKXQDURfBJUxY0EYR50',
    appId: '1:510409085828:ios:717b1b475d4b00931e03d1',
    messagingSenderId: '510409085828',
    projectId: 'healthybhai-b2791',
    storageBucket: 'healthybhai-b2791.firebasestorage.app',
    iosClientId: '510409085828-akfk75uc4doaap04t9mgnhlac35t218e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFivC3PsM8xTanFNfjtN5mlIUdIHq9arY',
    appId: '1:510409085828:web:c22952bca47745e31e03d1',
    messagingSenderId: '510409085828',
    projectId: 'healthybhai-b2791',
    authDomain: 'healthybhai-b2791.firebaseapp.com',
    storageBucket: 'healthybhai-b2791.firebasestorage.app',
  );
}
